add start:db script
FlarianWeb/cms-backend pull request #5
Opened 2024-02-10 05:46 UTC by barsukov-d

2024-02-10 19:56 UTC, MusinRamil requested changes
Открываю спор и запрашиваю изменения.

2024-02-10 19:56 UTC, MusinRamil commented on docker-compose.yml
> +        environment:
При первом запуске у меня не было ,env c переменными, получил вот такую ошибку:
```
WARN[0000] The "MYSQL_ROOT_USER" variable is not set. Defaulting to a blank string. 
WARN[0000] The "MYSQL_ROOT_PASSWORD" variable is not set. Defaulting to a blank string. 
WARN[0000] The "MYSQL_USER" variable is not set. Defaulting to a blank string. 
WARN[0000] The "MYSQL_PASSWORD" variable is not set. Defaulting to a blank string. 
WARN[0000] The "MYSQL_DATABASE" variable is not set. Defaulting to a blank string. 
WARN[0000] The "MYSQL_PORT" variable is not set. Defaulting to a blank string. 
```

1. Нужно создать `.env.dist` с точной копией `.env` за исключением того что все параметры должны быть 2. закомментированы. То-есть приложение даже если нет .env должно запускаться в дев режиме.
3. Префикс `MYSQL_` мне кажется лучше заменить на `DB_` так как может быть какой то другой драйвер бд.
4. Надо везде где используется env переменная захороводить переменную по умолчанию, можно в корне проекта создать файлик ids.ts если есть необходимость дефолтные значения использовать в нескольких местах.

2024-02-10 19:56 UTC, MusinRamil commented on docker-compose.yml
> +        environment:
Я не увидел тут host, наверное он тут не нужен?

2024-02-10 19:56 UTC, MusinRamil commented on src/app.module.ts
> +			dialect: 'mysql',
Вот это можно вынести в .env тоже но обязательно должно быть значение по дефолту чтобы при отсутствии .env приложение запускалось.

2024-02-10 19:56 UTC, MusinRamil commented on src/app.module.ts
> +		SequelizeModule.forRoot({
Все переменные надо вынести в .env и сделать им стандартные значения, они пересекаются с конфигом для докера, по этому возможно стоит вынести это в что то типа дефолтного глобального конфига...

2024-02-10 19:56 UTC, MusinRamil commented on package.json
>  {
Когда меняется package.json или добавляется команда хорошо бы вносить изменения в README.md

Я думаю что надо всё стандартное из него убрать и написать мини инструкцию по старту приложения, а также мини инструкцию по тестам.

А если добавить в него конфиг .env с описанием всех переменных и значений по умолчанию будет вообще супер!

2024-02-10 20:15 UTC, barsukov-d commented
Завтра все сделаю)

2024-02-10 20:35 UTC, MusinRamil requested changes
Нужно обсудить

2024-02-10 20:35 UTC, MusinRamil commented on scripts/db.js
> +async function checkDatabaseConnection(config) {
Может arrow function?
`const checkDatabaseConnection = async (config) => { ... }`

TODO: unit test

2024-02-10 20:35 UTC, MusinRamil commented on scripts/db.js
> +async function runCommands() {
`const runCommands = async () => { ... }`

TODO: unit test

2024-02-10 20:35 UTC, MusinRamil commented on scripts/db.js
> +		await new Promise(resolve => setTimeout(resolve, 5000)); // Wait for 5 seconds
таймаут подключения возможно стоит вынести в .env и глобальный дефолтный конфиг

2024-02-10 20:35 UTC, MusinRamil commented on scripts/db.js
> +		try {
Работу с `docker-compose up -d mysql-dev` мне кажется надо вынести в отдельную асинхронную функцию над `runCommands`

2024-02-10 20:35 UTC, MusinRamil commented on scripts/db.js
> +		console.log('Starting NestJS application...');
`console.log('Starting Application...');`

2024-02-10 20:35 UTC, MusinRamil commented on scripts/db.js
> +			console.log(`NestJS application exited with code ${code}`);
```console.log(`Application exited with code ${code}`);```

2024-02-10 20:35 UTC, MusinRamil commented on scripts/db.js
> +		const nestStart = spawn('nest', ['start']);
Всё что связано с запуском приложения может стоит вынести в функцию `applicationStart`?

`spawn('nest', ['start'])` - не совсем понимаю что тут происходит, если стартует приложение аналогично `pnpm start` то наверное стоит запуск переделать из `pnpm start:db` в что то другое... Надо обсудить

2024-02-11 14:31 UTC, barsukov-d commented on scripts/db.js
> +async function checkDatabaseConnection(config) {
Done

2024-02-11 14:33 UTC, barsukov-d commented on scripts/db.js
> +		await new Promise(resolve => setTimeout(resolve, 5000)); // Wait for 5 seconds
Done

2024-02-11 18:20 UTC, barsukov-d commented on docker-compose.yml
> +        environment:
Не нужно

2024-02-11 18:34 UTC, barsukov-d commented on docker-compose.yml
> +        environment:
я думаю .env.example это лучший вариант, всем понятно что делать )

2024-02-11 18:34 UTC, barsukov-d commented on package.json
>  {
Добавил

2024-02-11 19:39 UTC, MusinRamil approved these changes, later dismissed

2024-02-12 08:03 UTC, MusinRamil requested changes
Вроде это всё что нашёл.

2024-02-12 08:03 UTC, MusinRamil commented on .env.example
> +DB_HOST=                 # The hostname of your database server. For example: localhost
```
### The hostname of your database server.
### For example: localhost
DB_HOST=localhost

### The port your database server is running on.
### For example: 3306
DB_PORT=3306
```

2024-02-12 08:03 UTC, MusinRamil commented on .env.example
> +DB_ROOT_USER=            # The root user of your database. For example: root
Удаляем из env DB_ROOT_USER

2024-02-12 08:03 UTC, MusinRamil commented on .env.example
> +DB_ROOT_PASSWORD=        # The password for the root user of your database.
Удаляем из env DB_ROOT_PASSWORD

2024-02-12 08:03 UTC, MusinRamil commented on .env.example
> +DB_USER=                 # The user your application will use to connect to the database.
```
### The user your application will use to connect to the database.
### For example: root
DB_USER=root
```

2024-02-12 08:03 UTC, MusinRamil commented on .env.example
> +DB_PASSWORD=             # The password for the user your application will use to connect to the database.
```
### The password your application will use to connect to the database.
### For example: root
DB_PASSWORD=root
```

2024-02-12 08:03 UTC, MusinRamil commented on .env.example
> +DB_DATABASE=             # The name of the database your application will use.
```
### The name of the database your application will use.
### For example: flarian
DB_DATABASE=flarian
```

2024-02-12 08:03 UTC, MusinRamil commented on .env.example
> +# Database configuration
```
##################################################
### Database configuration
##################################################
```

2024-02-12 08:03 UTC, MusinRamil commented on .env.example
> +DB_PORT=                 # The port your database server is running on. For example: 3306
DB_PORT перенести вверх под DB_HOST

2024-02-12 08:03 UTC, MusinRamil commented on .env.example
> +DB_CONNECTION_TIMEOUT=   # The timeout for database connections, in milliseconds. For example: 5000
```
### The timeout for database connections, in milliseconds.
### For example: 5000
# DB_CONNECTION_TIMEOUT=5000
```

2024-02-12 08:03 UTC, MusinRamil commented on .env.example
> +# JWT configuration
```
##################################################
### JWT configuration
##################################################
```

2024-02-12 08:03 UTC, MusinRamil commented on .env.example
> +JWT_SECRET=              # The secret key used to sign JSON Web Tokens (JWTs) for authentication.
```
### The secret key used to sign JSON Web Tokens (JWTs) for authentication.
### For example: 5000
# JWT_SECRET=5000
```

2024-02-12 08:03 UTC, MusinRamil commented on README.md
> +$ pnpm run start:dev-db
`$ pnpm run start:dev-db`

Переносим в просто `pnpm run start:dev` пусть стартует с БД сразу и с флагом --watch

2024-02-12 08:03 UTC, MusinRamil commented on docker-compose.yml
> +            MYSQL_ROOT_USER: ${DB_ROOT_USER}
Тут хардкодим:
`MYSQL_ROOT_USER: root`

2024-02-12 08:03 UTC, MusinRamil commented on docker-compose.yml
> +            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
Тут хардкодим:
`MYSQL_ROOT_PASSWORD: root`

2024-02-12 08:03 UTC, MusinRamil commented on package.json
> +		"start:dev": "nest start --watch",
`"start:dev": "nest start --watch",`

меняем на:
`"start:dev": "node scripts/dev.js",`

Не забудь поменять название скрипта на `dev.js`

2024-02-12 08:03 UTC, MusinRamil commented on package.json
> +		"start:dev-db": "node scripts/dev-db.js",
`"start:dev-db": "node scripts/dev-db.js",`
убираем

2024-02-12 08:03 UTC, MusinRamil commented on scripts/dev-db.js
> +	const nestStart = spawn('nest', ['start']);
тут добавить флаг --watch

2024-02-12 08:03 UTC, MusinRamil commented on scripts/dev-db.js
> +const runCommands = async () => {
Где то в самом начале проверять наличие .env и если его нет, делаем копию .env.example и переименовываем в .env

2024-02-12 08:03 UTC, MusinRamil commented on scripts/dev-db.js
> +		console.log('Starting NestJS application...');
`console.log('Starting NestJS application...');`

меняем на:
`console.log('Starting Flarian application...');`

2024-02-12 08:03 UTC, MusinRamil commented on scripts/dev-db.js
> +		console.log(`NestJS application exited with code ${code}`);
`console.log(`NestJS application exited with code ${code}`);`

меняем на:
`console.log(`Flarian application exited with code ${code}`);`

2024-02-15 12:17 UTC, MusinRamil approved these changes
Good job!

2024-02-15 12:45 UTC, merged